application: sy-willet
version: 9
runtime: python
api_version: 1

handlers:
# serving tracking tweet generation iframe
- url: /(willet.html|trackErr)
  script: clicks/track.py

- url: /(fbCallback|sendEmailInvites|widget|willt|share|oauth.*)
  script: plugin/plugin.py

# queues that check our models for dead references
- url: /(StartRefCheck|CheckRef)
  script: util/db_queues.py

- url: /(campaignClicksCounter|emailerCron|emailerQueue|updateLanding|updateCounts|updateTweets|updateClicks)
  script: processes.py

- url: /conversion
  script: conversion.py

- url: /t/
  static_dir: clicks/static

- url: /mockup/
  static_dir: mockup

- url: /static
  static_dir: static

- url: /mixpanel
  script: mixpanel.py

- url: /(socialGraphAPI|klout)
  script: social_api.py

- url: /klout
  script: klout.py

# cron for checking if users tweeted
- url: /getTweets
  script: tweets/twitter.py

# client interaction with our website
- url: /
  script: website.py

# further client interactions
- url: /(about|account|deleteCampaign|login|logout|auth|register|campaign|campaign.json|contact|edit|doUpdateOrCreateCampaign|doFeedback|code|demo(.*))
  script: website.py

# website initialization
- url: /init.*
  script: init/setup.py
  
- url: /(admin|cleanBadLinks)
  script: admin.py

# links to track
- url: /.*
  script: clicks/track.py

